# Upload Dataset
POST http://127.0.0.1:5000/upload
Content-Type: multipart/form-data

file=@data/sample_data.csv

# Train Model
POST http://127.0.0.1:5000/train

# Predict Downtime
POST http://127.0.0.1:5000/predict
Content-Type: application/json

{
    "Temperature": 85,
    "Run_Time": 200
}
